homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Discover some devices automatically
discovery:

weather:
  - platform: darksky
    api_key: !secret darksky_apikey

wemo:
  discovery: true

tplink:
  discovery: true

ecobee:
  api_key: !secret ecobee_apikey

roku:
  - host: 10.83.25.196

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring

media_player:
  - platform: plex

speedtestdotnet:
  monitored_conditions:
    - download
    - upload

input_select:
  trevor_status_dropdown:
    name: Trevor
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

input_select:
  virginia_status_dropdown:
    name: Virginia
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

sensor:
  - platform: template
    sensors:
      trevor_status:
        value_template: '{{ states.input_select.trevor_status_dropdown.state }}'
        friendly_name: 'Trevor'
      virginia_status:
        value_template: '{{ states.input_select.virginia_status_dropdown.state }}'
        friendly_name: 'Virginia'

# Text to speech
tts:
  - platform: google

device_tracker: !include device-trackers.yaml
person: !include persons.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
