homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation_home
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

frontend:
  theme: !include theme.yaml

lovelace:
  mode: yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Discover some devices automatically
discovery:

weather:
  - platform: darksky
    api_key: !secret darksky_apikey

wemo:
  discovery: true

tplink:
  discovery: true

ecobee:
  api_key: !secret ecobee_apikey

roku:
  - host: 10.83.25.196

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring

media_player:
  - platform: plex

speedtestdotnet:
  monitored_conditions:
    - download
    - upload

# Text to speech
tts:
  - platform: google

device_tracker: !include device-trackers.yaml
person: !include persons.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
