title: Trevor's Home
views:
  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
        - type: weather-forecast
          entity: weather.dark_sky
      - type: entities
        title: Network Details
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
  - title: Thermostats
    icon: mdi:chart-line
    id: thermostats
    cards:
      - type: vertical-stack
        cards:
          - type: custom:simple-thermostat
            entity: climate.downstairs
            modes:
              auto: false
              auxHeatOnly: false
            hide:
              state: true
            sensors:
              - entity: sensor.downstairs_humidity
                name: Humidity
              - entity: sensor.downstairs_hvac_runtime
                name: Runtime
              - entity: sensor.downstairsthermoper
                name: Operation
      - type: vertical-stack
        cards:
          - type: custom:simple-thermostat
            entity: climate.upstairs
            modes:
              auto: false
              auxHeatOnly: false
            hide:
              state: true
            sensors:
              - entity: sensor.upstairs_humidity
                name: Humidity
              - entity: sensor.upstairs_hvac_runtime
                name: Runtime
              - entity: sensor.upstairsthermoper
                name: Operation