title: Trevor's Home
views:
  - title: Home
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
        - type: weather-forecast
          entity: weather.dark_sky
      - type: entities
        title: Network Details
        show_header_toggle: false
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
      - type: entities
        title: People Status
        entities:
          - groups.people_status
      - type: entities
        title: Lights
        entities:
          - switch.wemo_mini
          - switch.bedroom_lights
  - title: Thermostats
    icon: mdi:chart-line
    id: thermostats
    cards:
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.downstairs
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.upstairs